import Head from 'next/head'
import Header from '../components/header'
import Headericon from '../components/Headericon'
import Navbar from '../components/Navbar'
import Result from '../components/Result'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    {/* Header */}
      <Header/>
    
    {/* Navbar */}
      <Navbar/>
      <Headericon/>
    
    {/* Result */}
      <Result/>

    </div>
  )
}
